name: CD

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
jobs:
  deploy1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12
      - run: yarn
      - run: yarn build1
      - run: yarn firebase use github-actions-olocuga --token ${{ secrets.FIREBASE_TOKEN }}
      - run: yarn firebase deploy --only hosting:olocuga --non-interactive --token ${{ secrets.FIREBASE_TOKEN }} -m"olocuga"

  deploy2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12
      - run: yarn
      - run: yarn build2
      - run: yarn firebase use github-actions-olocuga --token ${{ secrets.FIREBASE_TOKEN }}
      - run: yarn firebase deploy --only hosting:volocuga --non-interactive --token ${{ secrets.FIREBASE_TOKEN }} -m"volocuga"
