name: CD

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
jobs:
  deploy1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12
      - run: yarn
      - run: yarn build
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:[github-actions-olocuga]
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
  deploy2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12
      - run: yarn
      - run: yarn build
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:[github-actions-volocuga]
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
