name: CD

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
jobs:
  deploy1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12
     - run: |
          yarn
          yarn build1
          yarn firebase deploy --only hosting -P olocuga --token ${{ secrets.FIREBASE_TOKEN }}
 
  deploy2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12
      - run: |
          yarn
          yarn build2
          yarn firebase deploy --only hosting -P volocuga --token ${{ secrets.FIREBASE_TOKEN }}
